### ISSUE TITLE
Issue whilr importing the ndjson file

### ISSUE THREAD

**Issue by HirenVikhram** [punk-security/smbeagle#66]
We are getting and issue when we import the export.ndjson file in kibana

Error Message:
"dashboard" which belongs to a more recent version of Kibana [7.15.0]. The last known version is [7.14.0]:

**Comment by hieronymusma** [comment]
I ran into the same issue. To fix this, you have to update the versions inside your `docker-compose.yml`.
`image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2` -> `image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0`
`image: docker.elastic.co/kibana/kibana:7.14.2` -> `image: docker.elastic.co/kibana/kibana:7.15.0`

**Comment by danieloateslee** [comment]
@hieronymusma thanks for the update ... I will investigate and get back to you shortly.

**Comment by HirenVikhram** [comment]
Thank you for resolving this issue sir.

Regards,
Hiren Vikhram S

**Comment by danieloateslee** [comment]
Confirmed and I will update the docker-compose file.
