### ISSUE TITLE
Username and Password required on none Windows platforms

### ISSUE THREAD

**Issue by Shiva108** [punk-security/SMBeagle#67]
Im on parrot linux.
Running so:
`docker run -v "./output/tmp/output" punksecurity/smbeagle -c /tmp/output/results.csv -n 10.10.10.0/24
`
Gives result:
ERROR: Username and Password required on none Windows platforms
Please advice.

**Comment by SimonGurney** [comment]
The target SMB server, you need to provide credentials to connect and scan.  If you are using it for a penetration test, I'd suggest starting by trying to find or bruteforce credentials
