### ISSUE TITLE
docker: Error response from daemon: create ./output: "./output"

### ISSUE THREAD

**Issue by allisonaaronb** [punk-security/smbeagle#83]
New to docker so it could be my lack of knowledge.

When trying to run the command below from the documentation, I am getting a docker error. If I remove the . from ./output it runs. What am I doing wrong?

docker run -v "./output:/tmp/output" punksecurity/smbeagle -c /tmp/output/results.csv -u USERNAME -p PASSWORD

docker: Error response from daemon: create ./output: "./output" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by SimonGurney** [comment]
Sorry for the insanely long time to get back to you.

You need to use an absolute path.  We'll update our docs


```docker run -v "$(pwd)/output:/tmp/output" punksecurity/smbeagle -c /tmp/output/results.csv -u USERNAME -p PASSWORD```
