### ISSUE TITLE
Ability to include inaccessible shares in output

### ISSUE THREAD

**Issue by rgorme** [punk-security/smbeagle#85]
Hi,

Thanks for your great work - this projec is very useful and appreciated!

When scanning for shares, only accessible shares are included in output.
Would it be possible to include shares that was found in the scanning process, but wasn't accessible?

It would be very useful for generating a complete list of shares on a server.

Best regards,

Rasmus

**Comment by SimonGurney** [comment]
Hi, 

Sorry for the slow response on this.  The ```-v``` flag should output all shares found :)  

Will this work, or would prefer we wrote it a file?
