### ISSUE TITLE
No useable version of libssl was found (Solution in description)

### ISSUE THREAD

**Issue by thec0nci3rge** [punk-security/smbeagle#87]
Hi guys, 

I am opening up this issue, as it might help anyone facing it as well. 

When downloading the **amd64.deb** version and running it for the first time - I get the following error:
```
No useable version of libssl was found
zsh: IOT instruction ./SMBeagle
```

![image](https://user-images.githubusercontent.com/65483817/233041361-56205912-4a64-475c-aae3-7c7c31b8945d.png)

Simply installing **libssl-dev** (`sudo apt install libssl-dev`) didn't solve it either (as it does in other cases). 

On a unity forum (https://forum.unity.com/threads/workaround-for-libssl-issue-on-ubuntu-22-04.1271405/), I was able to find a way to solve this, by simply installing an older libssl library for debian. 

`sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb`

Now, running `./SMBeagle --help` should work as intended.

I didn't have time to look inside the code, in order to find the culprit yet, however I thought this "quick fix" might be useful.

Greetings!

**Comment by SimonGurney** [comment]
Wow thanks for taking the time to find a fix for this.

We'll build a new version and see if that squashes this out :)

**Comment by SimonGurney** [comment]
This should be fixed as we've bumped to dotnet 7!  

We'd love for you test, but we've tested on old / new Kali and old / new Ubuntu!

**Comment by SimonGurney** [comment]
Wow, that's suspiciously close to a minute isn't it!

We've not seen that in our testing so I'm a bit stuck as to what it could be.  

There is very little actual code that runs as the arg parsing happens all right at the start and then throws that help message.

I'll see if I can reproduce it

**Comment by thec0nci3rge** [comment]
Okay, seems my WSL instance was running with issues. 

Testing it again, it is now a normal user experience:
![image](https://github.com/punk-security/smbeagle/assets/65483817/f65de6e8-1fe2-479d-b8a7-f6fc94c632c8)

So please disregard the time issue.

Happy to see it's working! Thank you again!

**Comment by SimonGurney** [comment]
ah ok brilliant, thanks for leeting us know :)
